package gomoji

// Complete emoji mapping database with most common face emojis and essential others
var emojiMappings = map[string]Mapping{
	// === HAPPY FACE EMOJIS ===
	"grinning": {
		Emoji:     "😀",
		Shortcode: ":grinning:",
		HTML:      "&#x1f600;",
		Unicode:   "\\U0001F600",
	},
	"grinning_eyes": {
		Emoji:     "😁",
		Shortcode: ":grinning_eyes:",
		HTML:      "&#x1f601;",
		Unicode:   "\\U0001F601",
	},
	"joy": {
		Emoji:     "😂",
		Shortcode: ":joy:",
		HTML:      "&#x1f602;",
		Unicode:   "\\U0001F602",
	},
	"smiley": {
		Emoji:     "😃",
		Shortcode: ":smiley:",
		HTML:      "&#x1f603;",
		Unicode:   "\\U0001F603",
	},
	"smile": {
		Emoji:     "😄",
		Shortcode: ":smile:",
		HTML:      "&#x1f604;",
		Unicode:   "\\U0001F604",
	},
	"sweat_smile": {
		Emoji:     "😅",
		Shortcode: ":sweat_smile:",
		HTML:      "&#x1f605;",
		Unicode:   "\\U0001F605",
	},
	"laughing": {
		Emoji:     "😆",
		Shortcode: ":laughing:",
		HTML:      "&#x1f606;",
		Unicode:   "\\U0001F606",
	},
	"wink": {
		Emoji:     "😉",
		Shortcode: ":wink:",
		HTML:      "&#x1f609;",
		Unicode:   "\\U0001F609",
	},
	"blush": {
		Emoji:     "😊",
		Shortcode: ":blush:",
		HTML:      "&#x1f60a;",
		Unicode:   "\\U0001F60A",
	},
	"yum": {
		Emoji:     "😋",
		Shortcode: ":yum:",
		HTML:      "&#x1f60b;",
		Unicode:   "\\U0001F60B",
	},

	// === NEUTRAL/COOL FACE EMOJIS ===
	"sunglasses": {
		Emoji:     "😎",
		Shortcode: ":sunglasses:",
		HTML:      "&#x1f60e;",
		Unicode:   "\\U0001F60E",
	},
	"heart_eyes": {
		Emoji:     "😍",
		Shortcode: ":heart_eyes:",
		HTML:      "&#x1f60d;",
		Unicode:   "\\U0001F60D",
	},
	"kissing_heart": {
		Emoji:     "😘",
		Shortcode: ":kissing_heart:",
		HTML:      "&#x1f618;",
		Unicode:   "\\U0001F618",
	},
	"kissing": {
		Emoji:     "😗",
		Shortcode: ":kissing:",
		HTML:      "&#x1f617;",
		Unicode:   "\\U0001F617",
	},
	"kissing_smiling_eyes": {
		Emoji:     "😙",
		Shortcode: ":kissing_smiling_eyes:",
		HTML:      "&#x1f619;",
		Unicode:   "\\U0001F619",
	},
	"kissing_closed_eyes": {
		Emoji:     "😚",
		Shortcode: ":kissing_closed_eyes:",
		HTML:      "&#x1f61a;",
		Unicode:   "\\U0001F61A",
	},
	"relaxed": {
		Emoji:     "☺️",
		Shortcode: ":relaxed:",
		HTML:      "&#x263a;&#xfe0f;",
		Unicode:   "\\U0000263A\\uFE0F",
	},
	"slight_smile": {
		Emoji:     "🙂",
		Shortcode: ":slight_smile:",
		HTML:      "&#x1f642;",
		Unicode:   "\\U0001F642",
	},
	"upside_down": {
		Emoji:     "🙃",
		Shortcode: ":upside_down:",
		HTML:      "&#x1f643;",
		Unicode:   "\\U0001F643",
	},

	// === THINKING/NEUTRAL FACE EMOJIS ===
	"thinking": {
		Emoji:     "🤔",
		Shortcode: ":thinking:",
		HTML:      "&#x1f914;",
		Unicode:   "\\U0001F914",
	},
	"neutral_face": {
		Emoji:     "😐",
		Shortcode: ":neutral_face:",
		HTML:      "&#x1f610;",
		Unicode:   "\\U0001F610",
	},
	"expressionless": {
		Emoji:     "😑",
		Shortcode: ":expressionless:",
		HTML:      "&#x1f611;",
		Unicode:   "\\U0001F611",
	},
	"no_mouth": {
		Emoji:     "😶",
		Shortcode: ":no_mouth:",
		HTML:      "&#x1f636;",
		Unicode:   "\\U0001F636",
	},

	// === SAD/CONCERNED FACE EMOJIS ===
	"confused": {
		Emoji:     "😕",
		Shortcode: ":confused:",
		HTML:      "&#x1f615;",
		Unicode:   "\\U0001F615",
	},
	"worried": {
		Emoji:     "😟",
		Shortcode: ":worried:",
		HTML:      "&#x1f61f;",
		Unicode:   "\\U0001F61F",
	},
	"slightly_frowning": {
		Emoji:     "🙁",
		Shortcode: ":slightly_frowning:",
		HTML:      "&#x1f641;",
		Unicode:   "\\U0001F641",
	},
	"frowning": {
		Emoji:     "☹️",
		Shortcode: ":frowning:",
		HTML:      "&#x2639;&#xfe0f;",
		Unicode:   "\\U00002639\\uFE0F",
	},
	"persevere": {
		Emoji:     "😣",
		Shortcode: ":persevere:",
		HTML:      "&#x1f623;",
		Unicode:   "\\U0001F623",
	},
	"confounded": {
		Emoji:     "😖",
		Shortcode: ":confounded:",
		HTML:      "&#x1f616;",
		Unicode:   "\\U0001F616",
	},
	"tired_face": {
		Emoji:     "😫",
		Shortcode: ":tired_face:",
		HTML:      "&#x1f62b;",
		Unicode:   "\\U0001F62B",
	},
	"weary": {
		Emoji:     "😩",
		Shortcode: ":weary:",
		HTML:      "&#x1f629;",
		Unicode:   "\\U0001F629",
	},
	"cry": {
		Emoji:     "😢",
		Shortcode: ":cry:",
		HTML:      "&#x1f622;",
		Unicode:   "\\U0001F622",
	},
	"sob": {
		Emoji:     "😭",
		Shortcode: ":sob:",
		HTML:      "&#x1f62d;",
		Unicode:   "\\U0001F62D",
	},

	// === ANGRY/UPSET FACE EMOJIS ===
	"angry": {
		Emoji:     "😠",
		Shortcode: ":angry:",
		HTML:      "&#x1f620;",
		Unicode:   "\\U0001F620",
	},
	"rage": {
		Emoji:     "😡",
		Shortcode: ":rage:",
		HTML:      "&#x1f621;",
		Unicode:   "\\U0001F621",
	},
	"triumph": {
		Emoji:     "😤",
		Shortcode: ":triumph:",
		HTML:      "&#x1f624;",
		Unicode:   "\\U0001F624",
	},

	// === SURPRISED/SHOCKED FACE EMOJIS ===
	"open_mouth": {
		Emoji:     "😮",
		Shortcode: ":open_mouth:",
		HTML:      "&#x1f62e;",
		Unicode:   "\\U0001F62E",
	},
	"scream": {
		Emoji:     "😱",
		Shortcode: ":scream:",
		HTML:      "&#x1f631;",
		Unicode:   "\\U0001F631",
	},
	"fearful": {
		Emoji:     "😨",
		Shortcode: ":fearful:",
		HTML:      "&#x1f628;",
		Unicode:   "\\U0001F628",
	},
	"cold_sweat": {
		Emoji:     "😰",
		Shortcode: ":cold_sweat:",
		HTML:      "&#x1f630;",
		Unicode:   "\\U0001F630",
	},
	"hushed": {
		Emoji:     "😯",
		Shortcode: ":hushed:",
		HTML:      "&#x1f62f;",
		Unicode:   "\\U0001F62F",
	},
	"flushed": {
		Emoji:     "😳",
		Shortcode: ":flushed:",
		HTML:      "&#x1f633;",
		Unicode:   "\\U0001F633",
	},

	// === SICK/UNWELL FACE EMOJIS ===
	"dizzy_face": {
		Emoji:     "😵",
		Shortcode: ":dizzy_face:",
		HTML:      "&#x1f635;",
		Unicode:   "\\U0001F635",
	},
	"mask": {
		Emoji:     "😷",
		Shortcode: ":mask:",
		HTML:      "&#x1f637;",
		Unicode:   "\\U0001F637",
	},

	// === ANIMALS ===
	"dog": {
		Emoji:     "🐶",
		Shortcode: ":dog:",
		HTML:      "&#x1f436;",
		Unicode:   "\\U0001F436",
	},
	"cat": {
		Emoji:     "🐱",
		Shortcode: ":cat:",
		HTML:      "&#x1f431;",
		Unicode:   "\\U0001F431",
	},
	"mouse": {
		Emoji:     "🐭",
		Shortcode: ":mouse:",
		HTML:      "&#x1f42d;",
		Unicode:   "\\U0001F42D",
	},
	"hamster": {
		Emoji:     "🐹",
		Shortcode: ":hamster:",
		HTML:      "&#x1f439;",
		Unicode:   "\\U0001F439",
	},
	"rabbit": {
		Emoji:     "🐰",
		Shortcode: ":rabbit:",
		HTML:      "&#x1f430;",
		Unicode:   "\\U0001F430",
	},
	"bear": {
		Emoji:     "🐻",
		Shortcode: ":bear:",
		HTML:      "&#x1f43b;",
		Unicode:   "\\U0001F43B",
	},
	"panda_face": {
		Emoji:     "🐼",
		Shortcode: ":panda_face:",
		HTML:      "&#x1f43c;",
		Unicode:   "\\U0001F43C",
	},
	"koala": {
		Emoji:     "🐨",
		Shortcode: ":koala:",
		HTML:      "&#x1f428;",
		Unicode:   "\\U0001F428",
	},
	"tiger": {
		Emoji:     "🐯",
		Shortcode: ":tiger:",
		HTML:      "&#x1f42f;",
		Unicode:   "\\U0001F42F",
	},
	"lion_face": {
		Emoji:     "🦁",
		Shortcode: ":lion_face:",
		HTML:      "&#x1f981;",
		Unicode:   "\\U0001F981",
	},
	"cow": {
		Emoji:     "🐮",
		Shortcode: ":cow:",
		HTML:      "&#x1f42e;",
		Unicode:   "\\U0001F42E",
	},
	"pig": {
		Emoji:     "🐷",
		Shortcode: ":pig:",
		HTML:      "&#x1f437;",
		Unicode:   "\\U0001F437",
	},
	"pig_nose": {
		Emoji:     "🐽",
		Shortcode: ":pig_nose:",
		HTML:      "&#x1f43d;",
		Unicode:   "\\U0001F43D",
	},
	"frog": {
		Emoji:     "🐸",
		Shortcode: ":frog:",
		HTML:      "&#x1f438;",
		Unicode:   "\\U0001F438",
	},
	"octopus": {
		Emoji:     "🐙",
		Shortcode: ":octopus:",
		HTML:      "&#x1f419;",
		Unicode:   "\\U0001F419",
	},
	"monkey_face": {
		Emoji:     "🐵",
		Shortcode: ":monkey_face:",
		HTML:      "&#x1f435;",
		Unicode:   "\\U0001F435",
	},
	"see_no_evil": {
		Emoji:     "🙈",
		Shortcode: ":see_no_evil:",
		HTML:      "&#x1f648;",
		Unicode:   "\\U0001F648",
	},
	"hear_no_evil": {
		Emoji:     "🙉",
		Shortcode: ":hear_no_evil:",
		HTML:      "&#x1f649;",
		Unicode:   "\\U0001F649",
	},
	"speak_no_evil": {
		Emoji:     "🙊",
		Shortcode: ":speak_no_evil:",
		HTML:      "&#x1f64a;",
		Unicode:   "\\U0001F64A",
	},

	// === HANDS AND GESTURES ===
	"thumbs_up": {
		Emoji:     "👍",
		Shortcode: ":thumbs_up:",
		HTML:      "&#x1f44d;",
		Unicode:   "\\U0001F44D",
	},
	"thumbs_down": {
		Emoji:     "👎",
		Shortcode: ":thumbs_down:",
		HTML:      "&#x1f44e;",
		Unicode:   "\\U0001F44E",
	},
	"clap": {
		Emoji:     "👏",
		Shortcode: ":clap:",
		HTML:      "&#x1f44f;",
		Unicode:   "\\U0001F44F",
	},
	"raised_hands": {
		Emoji:     "🙌",
		Shortcode: ":raised_hands:",
		HTML:      "&#x1f64c;",
		Unicode:   "\\U0001F64C",
	},
	"open_hands": {
		Emoji:     "👐",
		Shortcode: ":open_hands:",
		HTML:      "&#x1f450;",
		Unicode:   "\\U0001F450",
	},
	"point_up": {
		Emoji:     "☝️",
		Shortcode: ":point_up:",
		HTML:      "&#x261d;&#xfe0f;",
		Unicode:   "\\U0000261D\\uFE0F",
	},
	"point_down": {
		Emoji:     "👇",
		Shortcode: ":point_down:",
		HTML:      "&#x1f447;",
		Unicode:   "\\U0001F447",
	},
	"point_left": {
		Emoji:     "👈",
		Shortcode: ":point_left:",
		HTML:      "&#x1f448;",
		Unicode:   "\\U0001F448",
	},
	"point_right": {
		Emoji:     "👉",
		Shortcode: ":point_right:",
		HTML:      "&#x1f449;",
		Unicode:   "\\U0001F449",
	},
	"ok_hand": {
		Emoji:     "👌",
		Shortcode: ":ok_hand:",
		HTML:      "&#x1f44c;",
		Unicode:   "\\U0001F44C",
	},
	"peace": {
		Emoji:     "✌️",
		Shortcode: ":peace:",
		HTML:      "&#x270c;&#xfe0f;",
		Unicode:   "\\U0000270C\\uFE0F",
	},
	"crossed_fingers": {
		Emoji:     "🤞",
		Shortcode: ":crossed_fingers:",
		HTML:      "&#x1f91e;",
		Unicode:   "\\U0001F91E",
	},
	"metal": {
		Emoji:     "🤘",
		Shortcode: ":metal:",
		HTML:      "&#x1f918;",
		Unicode:   "\\U0001F918",
	},
	"call_me": {
		Emoji:     "🤙",
		Shortcode: ":call_me:",
		HTML:      "&#x1f919;",
		Unicode:   "\\U0001F919",
	},
	"fist": {
		Emoji:     "✊",
		Shortcode: ":fist:",
		HTML:      "&#x270a;",
		Unicode:   "\\U0000270A",
	},
	"punch": {
		Emoji:     "👊",
		Shortcode: ":punch:",
		HTML:      "&#x1f44a;",
		Unicode:   "\\U0001F44A",
	},
	"left_fist": {
		Emoji:     "🤛",
		Shortcode: ":left_fist:",
		HTML:      "&#x1f91b;",
		Unicode:   "\\U0001F91B",
	},
	"right_fist": {
		Emoji:     "🤜",
		Shortcode: ":right_fist:",
		HTML:      "&#x1f91c;",
		Unicode:   "\\U0001F91C",
	},
	"wave": {
		Emoji:     "👋",
		Shortcode: ":wave:",
		HTML:      "&#x1f44b;",
		Unicode:   "\\U0001F44B",
	},
	"pray": {
		Emoji:     "🙏",
		Shortcode: ":pray:",
		HTML:      "&#x1f64f;",
		Unicode:   "\\U0001F64F",
	},

	// === HEARTS ===
	"heart": {
		Emoji:     "❤️",
		Shortcode: ":heart:",
		HTML:      "&#x2764;&#xfe0f;",
		Unicode:   "\\U00002764\\uFE0F",
	},
	"yellow_heart": {
		Emoji:     "💛",
		Shortcode: ":yellow_heart:",
		HTML:      "&#x1f49b;",
		Unicode:   "\\U0001F49B",
	},
	"green_heart": {
		Emoji:     "💚",
		Shortcode: ":green_heart:",
		HTML:      "&#x1f49a;",
		Unicode:   "\\U0001F49A",
	},
	"blue_heart": {
		Emoji:     "💙",
		Shortcode: ":blue_heart:",
		HTML:      "&#x1f499;",
		Unicode:   "\\U0001F499",
	},
	"purple_heart": {
		Emoji:     "💜",
		Shortcode: ":purple_heart:",
		HTML:      "&#x1f49c;",
		Unicode:   "\\U0001F49C",
	},
	"black_heart": {
		Emoji:     "🖤",
		Shortcode: ":black_heart:",
		HTML:      "&#x1f5a4;",
		Unicode:   "\\U0001F5A4",
	},
	"broken_heart": {
		Emoji:     "💔",
		Shortcode: ":broken_heart:",
		HTML:      "&#x1f494;",
		Unicode:   "\\U0001F494",
	},
	"two_hearts": {
		Emoji:     "💕",
		Shortcode: ":two_hearts:",
		HTML:      "&#x1f495;",
		Unicode:   "\\U0001F495",
	},
	"sparkling_heart": {
		Emoji:     "💖",
		Shortcode: ":sparkling_heart:",
		HTML:      "&#x1f496;",
		Unicode:   "\\U0001F496",
	},
	"heartpulse": {
		Emoji:     "💗",
		Shortcode: ":heartpulse:",
		HTML:      "&#x1f497;",
		Unicode:   "\\U0001F497",
	},
	"cupid": {
		Emoji:     "💘",
		Shortcode: ":cupid:",
		HTML:      "&#x1f498;",
		Unicode:   "\\U0001F498",
	},

	// === SYMBOLS ===
	"star": {
		Emoji:     "⭐",
		Shortcode: ":star:",
		HTML:      "&#x2b50;",
		Unicode:   "\\U00002B50",
	},
	"star2": {
		Emoji:     "🌟",
		Shortcode: ":star2:",
		HTML:      "&#x1f31f;",
		Unicode:   "\\U0001F31F",
	},
	"fire": {
		Emoji:     "🔥",
		Shortcode: ":fire:",
		HTML:      "&#x1f525;",
		Unicode:   "\\U0001F525",
	},
	"boom": {
		Emoji:     "💥",
		Shortcode: ":boom:",
		HTML:      "&#x1f4a5;",
		Unicode:   "\\U0001F4A5",
	},
	"sparkles": {
		Emoji:     "✨",
		Shortcode: ":sparkles:",
		HTML:      "&#x2728;",
		Unicode:   "\\U00002728",
	},
	"zap": {
		Emoji:     "⚡",
		Shortcode: ":zap:",
		HTML:      "&#x26a1;",
		Unicode:   "\\U000026A1",
	},
	"gem": {
		Emoji:     "💎",
		Shortcode: ":gem:",
		HTML:      "&#x1f48e;",
		Unicode:   "\\U0001F48E",
	},

	// === NATURE ===
	"sunflower": {
		Emoji:     "🌻",
		Shortcode: ":sunflower:",
		HTML:      "&#x1f33b;",
		Unicode:   "\\U0001F33B",
	},
	"rose": {
		Emoji:     "🌹",
		Shortcode: ":rose:",
		HTML:      "&#x1f339;",
		Unicode:   "\\U0001F339",
	},
	"tulip": {
		Emoji:     "🌷",
		Shortcode: ":tulip:",
		HTML:      "&#x1f337;",
		Unicode:   "\\U0001F337",
	},
	"cherry_blossom": {
		Emoji:     "🌸",
		Shortcode: ":cherry_blossom:",
		HTML:      "&#x1f338;",
		Unicode:   "\\U0001F338",
	},
	"blossom": {
		Emoji:     "🌼",
		Shortcode: ":blossom:",
		HTML:      "&#x1f33c;",
		Unicode:   "\\U0001F33C",
	},
	"hibiscus": {
		Emoji:     "🌺",
		Shortcode: ":hibiscus:",
		HTML:      "&#x1f33a;",
		Unicode:   "\\U0001F33A",
	},
	"sun": {
		Emoji:     "☀️",
		Shortcode: ":sun:",
		HTML:      "&#x2600;&#xfe0f;",
		Unicode:   "\\U00002600\\uFE0F",
	},
	"partly_sunny": {
		Emoji:     "⛅",
		Shortcode: ":partly_sunny:",
		HTML:      "&#x26c5;",
		Unicode:   "\\U000026C5",
	},
	"cloud": {
		Emoji:     "☁️",
		Shortcode: ":cloud:",
		HTML:      "&#x2601;&#xfe0f;",
		Unicode:   "\\U00002601\\uFE0F",
	},
	"rain_cloud": {
		Emoji:     "🌧️",
		Shortcode: ":rain_cloud:",
		HTML:      "&#x1f327;&#xfe0f;",
		Unicode:   "\\U0001F327\\uFE0F",
	},
	"snowman": {
		Emoji:     "⛄",
		Shortcode: ":snowman:",
		HTML:      "&#x26c4;",
		Unicode:   "\\U000026C4",
	},
	"snowflake": {
		Emoji:     "❄️",
		Shortcode: ":snowflake:",
		HTML:      "&#x2744;&#xfe0f;",
		Unicode:   "\\U00002744\\uFE0F",
	},
	"rainbow": {
		Emoji:     "🌈",
		Shortcode: ":rainbow:",
		HTML:      "&#x1f308;",
		Unicode:   "\\U0001F308",
	},

	// === FOOD ===
	"apple": {
		Emoji:     "🍎",
		Shortcode: ":apple:",
		HTML:      "&#x1f34e;",
		Unicode:   "\\U0001F34E",
	},
	"banana": {
		Emoji:     "🍌",
		Shortcode: ":banana:",
		HTML:      "&#x1f34c;",
		Unicode:   "\\U0001F34C",
	},
	"grapes": {
		Emoji:     "🍇",
		Shortcode: ":grapes:",
		HTML:      "&#x1f347;",
		Unicode:   "\\U0001F347",
	},
	"strawberry": {
		Emoji:     "🍓",
		Shortcode: ":strawberry:",
		HTML:      "&#x1f353;",
		Unicode:   "\\U0001F353",
	},
	"watermelon": {
		Emoji:     "🍉",
		Shortcode: ":watermelon:",
		HTML:      "&#x1f349;",
		Unicode:   "\\U0001F349",
	},
	"orange": {
		Emoji:     "🍊",
		Shortcode: ":orange:",
		HTML:      "&#x1f34a;",
		Unicode:   "\\U0001F34A",
	},
	"lemon": {
		Emoji:     "🍋",
		Shortcode: ":lemon:",
		HTML:      "&#x1f34b;",
		Unicode:   "\\U0001F34B",
	},
	"peach": {
		Emoji:     "🍑",
		Shortcode: ":peach:",
		HTML:      "&#x1f351;",
		Unicode:   "\\U0001F351",
	},
	"cherries": {
		Emoji:     "🍒",
		Shortcode: ":cherries:",
		HTML:      "&#x1f352;",
		Unicode:   "\\U0001F352",
	},
	"pineapple": {
		Emoji:     "🍍",
		Shortcode: ":pineapple:",
		HTML:      "&#x1f34d;",
		Unicode:   "\\U0001F34D",
	},
	"pizza": {
		Emoji:     "🍕",
		Shortcode: ":pizza:",
		HTML:      "&#x1f355;",
		Unicode:   "\\U0001F355",
	},
	"hamburger": {
		Emoji:     "🍔",
		Shortcode: ":hamburger:",
		HTML:      "&#x1f354;",
		Unicode:   "\\U0001F354",
	},
	"hotdog": {
		Emoji:     "🌭",
		Shortcode: ":hotdog:",
		HTML:      "&#x1f32d;",
		Unicode:   "\\U0001F32D",
	},
	"taco": {
		Emoji:     "🌮",
		Shortcode: ":taco:",
		HTML:      "&#x1f32e;",
		Unicode:   "\\U0001F32E",
	},
	"burrito": {
		Emoji:     "🌯",
		Shortcode: ":burrito:",
		HTML:      "&#x1f32f;",
		Unicode:   "\\U0001F32F",
	},

	// === DRINKS ===
	"coffee": {
		Emoji:     "☕",
		Shortcode: ":coffee:",
		HTML:      "&#x2615;",
		Unicode:   "\\U00002615",
	},
	"tea": {
		Emoji:     "🍵",
		Shortcode: ":tea:",
		HTML:      "&#x1f375;",
		Unicode:   "\\U0001F375",
	},
	"beer": {
		Emoji:     "🍺",
		Shortcode: ":beer:",
		HTML:      "&#x1f37a;",
		Unicode:   "\\U0001F37A",
	},
	"beers": {
		Emoji:     "🍻",
		Shortcode: ":beers:",
		HTML:      "&#x1f37b;",
		Unicode:   "\\U0001F37B",
	},
	"wine_glass": {
		Emoji:     "🍷",
		Shortcode: ":wine_glass:",
		HTML:      "&#x1f377;",
		Unicode:   "\\U0001F377",
	},
	"cocktail": {
		Emoji:     "🍸",
		Shortcode: ":cocktail:",
		HTML:      "&#x1f378;",
		Unicode:   "\\U0001F378",
	},

	// === SPORTS & ACTIVITIES ===
	"soccer": {
		Emoji:     "⚽",
		Shortcode: ":soccer:",
		HTML:      "&#x26bd;",
		Unicode:   "\\U000026BD",
	},
	"basketball": {
		Emoji:     "🏀",
		Shortcode: ":basketball:",
		HTML:      "&#x1f3c0;",
		Unicode:   "\\U0001F3C0",
	},
	"football": {
		Emoji:     "🏈",
		Shortcode: ":football:",
		HTML:      "&#x1f3c8;",
		Unicode:   "\\U0001F3C8",
	},
	"tennis": {
		Emoji:     "🎾",
		Shortcode: ":tennis:",
		HTML:      "&#x1f3be;",
		Unicode:   "\\U0001F3BE",
	},
	"8ball": {
		Emoji:     "🎱",
		Shortcode: ":8ball:",
		HTML:      "&#x1f3b1;",
		Unicode:   "\\U0001F3B1",
	},
	"golf": {
		Emoji:     "⛳",
		Shortcode: ":golf:",
		HTML:      "&#x26f3;",
		Unicode:   "\\U000026F3",
	},

	// === TRANSPORTATION ===
	"car": {
		Emoji:     "🚗",
		Shortcode: ":car:",
		HTML:      "&#x1f697;",
		Unicode:   "\\U0001F697",
	},
	"taxi": {
		Emoji:     "🚕",
		Shortcode: ":taxi:",
		HTML:      "&#x1f695;",
		Unicode:   "\\U0001F695",
	},
	"bus": {
		Emoji:     "🚌",
		Shortcode: ":bus:",
		HTML:      "&#x1f68c;",
		Unicode:   "\\U0001F68C",
	},
	"train": {
		Emoji:     "🚆",
		Shortcode: ":train:",
		HTML:      "&#x1f686;",
		Unicode:   "\\U0001F686",
	},
	"airplane": {
		Emoji:     "✈️",
		Shortcode: ":airplane:",
		HTML:      "&#x2708;&#xfe0f;",
		Unicode:   "\\U00002708\\uFE0F",
	},
	"rocket": {
		Emoji:     "🚀",
		Shortcode: ":rocket:",
		HTML:      "&#x1f680;",
		Unicode:   "\\U0001F680",
	},
	"ship": {
		Emoji:     "🚢",
		Shortcode: ":ship:",
		HTML:      "&#x1f6a2;",
		Unicode:   "\\U0001F6A2",
	},
	"bike": {
		Emoji:     "🚲",
		Shortcode: ":bike:",
		HTML:      "&#x1f6b2;",
		Unicode:   "\\U0001F6B2",
	},

	// === OBJECTS ===
	"phone": {
		Emoji:     "📱",
		Shortcode: ":phone:",
		HTML:      "&#x1f4f1;",
		Unicode:   "\\U0001F4F1",
	},
	"computer": {
		Emoji:     "💻",
		Shortcode: ":computer:",
		HTML:      "&#x1f4bb;",
		Unicode:   "\\U0001F4BB",
	},
	"keyboard": {
		Emoji:     "⌨️",
		Shortcode: ":keyboard:",
		HTML:      "&#x2328;&#xfe0f;",
		Unicode:   "\\U00002328\\uFE0F",
	},
	"mouse_three_button": {
		Emoji:     "🖱️",
		Shortcode: ":mouse_three_button:",
		HTML:      "&#x1f5b1;&#xfe0f;",
		Unicode:   "\\U0001F5B1\\uFE0F",
	},
	"camera": {
		Emoji:     "📷",
		Shortcode: ":camera:",
		HTML:      "&#x1f4f7;",
		Unicode:   "\\U0001F4F7",
	},
	"tv": {
		Emoji:     "📺",
		Shortcode: ":tv:",
		HTML:      "&#x1f4fa;",
		Unicode:   "\\U0001F4FA",
	},
	"radio": {
		Emoji:     "📻",
		Shortcode: ":radio:",
		HTML:      "&#x1f4fb;",
		Unicode:   "\\U0001F4FB",
	},
	"headphones": {
		Emoji:     "🎧",
		Shortcode: ":headphones:",
		HTML:      "&#x1f3a7;",
		Unicode:   "\\U0001F3A7",
	},
	"microphone": {
		Emoji:     "🎤",
		Shortcode: ":microphone:",
		HTML:      "&#x1f3a4;",
		Unicode:   "\\U0001F3A4",
	},
	"musical_note": {
		Emoji:     "🎵",
		Shortcode: ":musical_note:",
		HTML:      "&#x1f3b5;",
		Unicode:   "\\U0001F3B5",
	},
	"notes": {
		Emoji:     "🎶",
		Shortcode: ":notes:",
		HTML:      "&#x1f3b6;",
		Unicode:   "\\U0001F3B6",
	},
	"guitar": {
		Emoji:     "🎸",
		Shortcode: ":guitar:",
		HTML:      "&#x1f3b8;",
		Unicode:   "\\U0001F3B8",
	},
	"trumpet": {
		Emoji:     "🎺",
		Shortcode: ":trumpet:",
		HTML:      "&#x1f3ba;",
		Unicode:   "\\U0001F3BA",
	},
	"saxophone": {
		Emoji:     "🎷",
		Shortcode: ":saxophone:",
		HTML:      "&#x1f3b7;",
		Unicode:   "\\U0001F3B7",
	},

	// === FLAGS (a few common ones) ===
	"flag_us": {
		Emoji:     "🇺🇸",
		Shortcode: ":flag_us:",
		HTML:      "&#x1f1fa;&#x1f1f8;",
		Unicode:   "\\U0001F1FA\\U0001F1F8",
	},
	"flag_gb": {
		Emoji:     "🇬🇧",
		Shortcode: ":flag_gb:",
		HTML:      "&#x1f1ec;&#x1f1e7;",
		Unicode:   "\\U0001F1EC\\U0001F1E7",
	},
	"flag_fr": {
		Emoji:     "🇫🇷",
		Shortcode: ":flag_fr:",
		HTML:      "&#x1f1eb;&#x1f1f7;",
		Unicode:   "\\U0001F1EB\\U0001F1F7",
	},
	"flag_de": {
		Emoji:     "🇩🇪",
		Shortcode: ":flag_de:",
		HTML:      "&#x1f1e9;&#x1f1ea;",
		Unicode:   "\\U0001F1E9\\U0001F1EA",
	},
	"flag_jp": {
		Emoji:     "🇯🇵",
		Shortcode: ":flag_jp:",
		HTML:      "&#x1f1ef;&#x1f1f5;",
		Unicode:   "\\U0001F1EF\\U0001F1F5",
	},
	"flag_cn": {
		Emoji:     "🇨🇳",
		Shortcode: ":flag_cn:",
		HTML:      "&#x1f1e8;&#x1f1f3;",
		Unicode:   "\\U0001F1E8\\U0001F1F3",
	},
}
